version: 0.0
os: linux

file_exists_behavior: OVERWRITE   # 🔥 ADD THIS

files:
  - source: /
    destination: /home/ec2-user/urlshortener

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
